// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Tue Dec  5 19:49:36 2023

Mux8_4b Mux8_4b_inst
(
	.S2(S2_sig) ,	// input  S2_sig
	.S1(S1_sig) ,	// input  S1_sig
	.S0(S0_sig) ,	// input  S0_sig
	.W0(W0_sig) ,	// input [3:0] W0_sig
	.W1(W1_sig) ,	// input [3:0] W1_sig
	.W2(W2_sig) ,	// input [3:0] W2_sig
	.W3(W3_sig) ,	// input [3:0] W3_sig
	.W4(W4_sig) ,	// input [3:0] W4_sig
	.W5(W5_sig) ,	// input [3:0] W5_sig
	.W6(W6_sig) ,	// input [3:0] W6_sig
	.W7(W7_sig) ,	// input [3:0] W7_sig
	.F(F_sig) 	// output [3:0] F_sig
);

